# Generated by Django 4.0.3 on 2022-04-20 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetworks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link_sn', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='StatusUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', models.ImageField(upload_to='img')),
                ('type_user', models.CharField(choices=[('Back End', 'Back End'), ('Front End', 'Front End'), ('Full Stack', 'Full Stack')], default='Full Stack', max_length=11)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('social_networks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='status.socialnetworks')),
            ],
            options={
                'verbose_name': 'StatusUserModel',
                'verbose_name_plural': 'StatusUserModels',
                'ordering': ['id'],
            },
        ),
    ]
